version: '3.5'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: fettle-milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /www/wwwroot/fettle-standalone/deploy/milvus/data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    restart: always

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: fettle-milvus-minio
    environment:
      MINIO_ACCESS_KEY: CHANGE_ME
      MINIO_SECRET_KEY: CHANGE_ME
    volumes:
      - /www/wwwroot/fettle-standalone/deploy/milvus/data/minio:/minio_data
    command: minio server /minio_data --console-address :9001
    ports:
      - "9010:9000"
      - "9011:9001"
    restart: always

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: fettle-milvus
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - /www/wwwroot/fettle-standalone/deploy/milvus/data/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    restart: always
