apiVersion: v1
kind: Secret
metadata:
  name: fettle-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.global.jwtSecret | quote }}
  db-password: {{ .Values.infra.postgres.password | quote }}
