# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.ai_engine_pb2 as ai__engine__pb2

GRPC_GENERATED_VERSION = '1.82.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIEngineStub:
    """AI 引擎服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeIntent = channel.unary_unary(
                '/ai_engine.AIEngine/RecognizeIntent',
                request_serializer=ai__engine__pb2.IntentRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.IntentResponse.FromString,
                _registered_method=True)
        self.PlanTask = channel.unary_unary(
                '/ai_engine.AIEngine/PlanTask',
                request_serializer=ai__engine__pb2.PlanRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.GenerateReply = channel.unary_unary(
                '/ai_engine.AIEngine/GenerateReply',
                request_serializer=ai__engine__pb2.ReplyRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.ReplyResponse.FromString,
                _registered_method=True)
        self.StreamReply = channel.unary_stream(
                '/ai_engine.AIEngine/StreamReply',
                request_serializer=ai__engine__pb2.StreamRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/ai_engine.AIEngine/GenerateEmbedding',
                request_serializer=ai__engine__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.RetrieveKnowledge = channel.unary_unary(
                '/ai_engine.AIEngine/RetrieveKnowledge',
                request_serializer=ai__engine__pb2.KnowledgeRequest.SerializeToString,
                response_deserializer=ai__engine__pb2.KnowledgeResponse.FromString,
                _registered_method=True)


class AIEngineServicer:
    """AI 引擎服务定义
    """

    def RecognizeIntent(self, request, context):
        """意图识别
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanTask(self, request, context):
        """任务规划
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReply(self, request, context):
        """回复生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReply(self, request, context):
        """流式回复
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """嵌入生成
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveKnowledge(self, request, context):
        """知识检索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeIntent,
                    request_deserializer=ai__engine__pb2.IntentRequest.FromString,
                    response_serializer=ai__engine__pb2.IntentResponse.SerializeToString,
            ),
            'PlanTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanTask,
                    request_deserializer=ai__engine__pb2.PlanRequest.FromString,
                    response_serializer=ai__engine__pb2.PlanResponse.SerializeToString,
            ),
            'GenerateReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReply,
                    request_deserializer=ai__engine__pb2.ReplyRequest.FromString,
                    response_serializer=ai__engine__pb2.ReplyResponse.SerializeToString,
            ),
            'StreamReply': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamReply,
                    request_deserializer=ai__engine__pb2.StreamRequest.FromString,
                    response_serializer=ai__engine__pb2.StreamResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=ai__engine__pb2.EmbeddingRequest.FromString,
                    response_serializer=ai__engine__pb2.EmbeddingResponse.SerializeToString,
            ),
            'RetrieveKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveKnowledge,
                    request_deserializer=ai__engine__pb2.KnowledgeRequest.FromString,
                    response_serializer=ai__engine__pb2.KnowledgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_engine.AIEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_engine.AIEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIEngine:
    """AI 引擎服务定义
    """

    @staticmethod
    def RecognizeIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/RecognizeIntent',
            ai__engine__pb2.IntentRequest.SerializeToString,
            ai__engine__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/PlanTask',
            ai__engine__pb2.PlanRequest.SerializeToString,
            ai__engine__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/GenerateReply',
            ai__engine__pb2.ReplyRequest.SerializeToString,
            ai__engine__pb2.ReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_engine.AIEngine/StreamReply',
            ai__engine__pb2.StreamRequest.SerializeToString,
            ai__engine__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/GenerateEmbedding',
            ai__engine__pb2.EmbeddingRequest.SerializeToString,
            ai__engine__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_engine.AIEngine/RetrieveKnowledge',
            ai__engine__pb2.KnowledgeRequest.SerializeToString,
            ai__engine__pb2.KnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
