// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: ai_engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIEngine_RecognizeIntent_FullMethodName   = "/ai_engine.AIEngine/RecognizeIntent"
	AIEngine_PlanTask_FullMethodName          = "/ai_engine.AIEngine/PlanTask"
	AIEngine_GenerateReply_FullMethodName     = "/ai_engine.AIEngine/GenerateReply"
	AIEngine_StreamReply_FullMethodName       = "/ai_engine.AIEngine/StreamReply"
	AIEngine_GenerateEmbedding_FullMethodName = "/ai_engine.AIEngine/GenerateEmbedding"
	AIEngine_RetrieveKnowledge_FullMethodName = "/ai_engine.AIEngine/RetrieveKnowledge"
)

// AIEngineClient is the client API for AIEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIEngineClient interface {
	RecognizeIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error)
	PlanTask(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	GenerateReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error)
	StreamReply(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (AIEngine_StreamReplyClient, error)
	GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	RetrieveKnowledge(ctx context.Context, in *KnowledgeRequest, opts ...grpc.CallOption) (*KnowledgeResponse, error)
}

type aIEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAIEngineClient(cc grpc.ClientConnInterface) AIEngineClient {
	return &aIEngineClient{cc}
}

func (c *aIEngineClient) RecognizeIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error) {
	out := new(IntentResponse)
	err := c.cc.Invoke(ctx, AIEngine_RecognizeIntent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineClient) PlanTask(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, AIEngine_PlanTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineClient) GenerateReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*ReplyResponse, error) {
	out := new(ReplyResponse)
	err := c.cc.Invoke(ctx, AIEngine_GenerateReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineClient) StreamReply(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (AIEngine_StreamReplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIEngine_ServiceDesc.Streams[0], AIEngine_StreamReply_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aIEngineStreamReplyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIEngine_StreamReplyClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type aIEngineStreamReplyClient struct {
	grpc.ClientStream
}

func (x *aIEngineStreamReplyClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIEngineClient) GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, AIEngine_GenerateEmbedding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIEngineClient) RetrieveKnowledge(ctx context.Context, in *KnowledgeRequest, opts ...grpc.CallOption) (*KnowledgeResponse, error) {
	out := new(KnowledgeResponse)
	err := c.cc.Invoke(ctx, AIEngine_RetrieveKnowledge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIEngineServer is the server API for AIEngine service.
// All implementations must embed UnimplementedAIEngineServer
// for forward compatibility
type AIEngineServer interface {
	RecognizeIntent(context.Context, *IntentRequest) (*IntentResponse, error)
	PlanTask(context.Context, *PlanRequest) (*PlanResponse, error)
	GenerateReply(context.Context, *ReplyRequest) (*ReplyResponse, error)
	StreamReply(*StreamRequest, AIEngine_StreamReplyServer) error
	GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	RetrieveKnowledge(context.Context, *KnowledgeRequest) (*KnowledgeResponse, error)
	mustEmbedUnimplementedAIEngineServer()
}

// UnimplementedAIEngineServer must be embedded to have forward compatible implementations.
type UnimplementedAIEngineServer struct {
}

func (UnimplementedAIEngineServer) RecognizeIntent(context.Context, *IntentRequest) (*IntentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecognizeIntent not implemented")
}
func (UnimplementedAIEngineServer) PlanTask(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanTask not implemented")
}
func (UnimplementedAIEngineServer) GenerateReply(context.Context, *ReplyRequest) (*ReplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateReply not implemented")
}
func (UnimplementedAIEngineServer) StreamReply(*StreamRequest, AIEngine_StreamReplyServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamReply not implemented")
}
func (UnimplementedAIEngineServer) GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedAIEngineServer) RetrieveKnowledge(context.Context, *KnowledgeRequest) (*KnowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveKnowledge not implemented")
}
func (UnimplementedAIEngineServer) mustEmbedUnimplementedAIEngineServer() {}

// UnsafeAIEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIEngineServer will
// result in compilation errors.
type UnsafeAIEngineServer interface {
	mustEmbedUnimplementedAIEngineServer()
}

func RegisterAIEngineServer(s grpc.ServiceRegistrar, srv AIEngineServer) {
	s.RegisterService(&AIEngine_ServiceDesc, srv)
}

func _AIEngine_RecognizeIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).RecognizeIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_RecognizeIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).RecognizeIntent(ctx, req.(*IntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngine_PlanTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).PlanTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_PlanTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).PlanTask(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngine_GenerateReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).GenerateReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_GenerateReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).GenerateReply(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngine_StreamReply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIEngineServer).StreamReply(m, &aIEngineStreamReplyServer{stream})
}

type AIEngine_StreamReplyServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type aIEngineStreamReplyServer struct {
	grpc.ServerStream
}

func (x *aIEngineStreamReplyServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AIEngine_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).GenerateEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIEngine_RetrieveKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).RetrieveKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_RetrieveKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).RetrieveKnowledge(ctx, req.(*KnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIEngine_ServiceDesc is the grpc.ServiceDesc for AIEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_engine.AIEngine",
	HandlerType: (*AIEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecognizeIntent",
			Handler:    _AIEngine_RecognizeIntent_Handler,
		},
		{
			MethodName: "PlanTask",
			Handler:    _AIEngine_PlanTask_Handler,
		},
		{
			MethodName: "GenerateReply",
			Handler:    _AIEngine_GenerateReply_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _AIEngine_GenerateEmbedding_Handler,
		},
		{
			MethodName: "RetrieveKnowledge",
			Handler:    _AIEngine_RetrieveKnowledge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReply",
			Handler:       _AIEngine_StreamReply_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai_engine.proto",
}
